/*******************************************************************************
 * Copyright (c) 2007 Ryan Rusaw, some portions (c) 2005, 2007 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Ryan Rusaw
 *******************************************************************************/
package org.seisint.eclide.core;

public class OctaveKeywords implements IOctaveKeywords {
	
	private static final String[] octaveReserved1 = {
		"abs",
		"acos",
		"ascii",
		"asin",
		"asstring",
		"atan",
		"atan2",
		"ave",
		"case",
		"choose",
		"choosen",
		"choosesets",
		"clustersize",
		"cos",
		"cosh",
		"count",
		"cron",
		"dataset",
		"dedup",
		"denormalize",
		"distribute",
		"distributed",
		"distribution",
		"ebcdic",
		"enth",
		"error",
		"evaluate",
		"event",
		"exists",
		"exp",
		"fetch",
		"fromunicode",
		"getisvalid",
		"global",
		"group",
		"hash",
		"hash32",
		"hash64",
		"hashcrc",
		"hashmd5",
		"if",
		"index",
		"intformat",
		"isvalid",
		"iterate",
		"join",
		"keyunicode",
		"length",
		"limit",
		"ln",
		"log",
		"map",
		"matched",
		"matchlength",
		"matchposition",
		"matchtext",
		"matchunicode",
		"max",
		"merge",
		"min",
		"normalize",
		"parse",
		"pipe",
		"power",
		"preload",
		"project",
		"pull",
		"random",
		"rank",
		"ranked",
		"realformat",
		"recordof",
		"regexfind",
		"regexreplace",
		"rejected",
		"rollup",
		"round",
		"roundup",
		"row",
		"rowdiff",
		"sample",
		"set",
		"sin",
		"sinh",
		"sizeof",
		"soapcall",
		"sort",
		"sorted",
		"sqrt",
		"sum",
		"table",
		"tan",
		"tanh",
		"topn",
		"tounicode",
		"transfer",
		"trim",
		"truncate",
		"typeof",
		"ungroup",
		"unicodeorder",
		"which",
		"workunit",
		"xmldecode",
		"xmlencode",
		"xmltext",
		"xmlunicode"
	};
	
	private static final String[] octaveReserved2 = {
		"apply",
		"build",
		"buildindex",
		"evaluate",
		"fail",
		"keydiff",
		"keypatch",
		"loadxml",
		"notify",
		"output",
		"parallel",
		"sequential",
		"soapcall"
	};
	
	private static final String[] octaveReserved3 = {
		"all",
		"and",
		"any",
		"as",
		"atmost",
		"before",
		"beginc++",
		"best",
		"between",
		"case",
		"const",
		"counter",
		"csv",
		"descend",
		"encrypt",
		"end",
		"endc++",
		"endmacro",
		"except",
		"exclusive",
		"expire",
		"export",
		"extend",
		"false",
		"few",
		"first",
		"flat",
		"full",
		"function",
		"group",
		"header",
		"heading",
		"hole",
		"ifblock",
		"import",
		"in",
		"joined",
		"keep",
		"keyed",
		"last",
		"left",
		"limit",
		"load",
		"local",
		"locale",
		"lookup",
		"macro",
		"many",
		"maxcount",
		"maxlength",
		"min skew",
		"module",
		"named",
		"nocase(",
		"noroot",
		"noscan",
		"nosort",
		"not",
		"of",
		"only",
		"opt",
		"or",
		"outer",
		"overwrite",
		"packed",
		"partition",
		"penalty",
		"physicallength",
		"pipe",
		"quote",
		"record",
		"relationship",
		"repeat",
		"return",
		"right",
		"scan",
		"self",
		"separator",
		"service",
		"shared",
		"skew",
		"skip",
		"sql",
		"store",
		"terminator",
		"thor",
		"threshold",
		"token",
		"transform",
		"trim",
		"true",
		"type",
		"unicodeorder",
		"unsorted",
		"validate",
		"virtual",
		"whole",
		"wild",
		"within",
		"xml",
		"xpath",
		"__compressed__"
	};
	
	private static final String[] octaveReserved4 = {
		"ascii",
		"big_endian",
		"boolean",
		"data",
		"decimal",
		"ebcdic",
		"integer",
		"pattern",
		"qstring",
		"real",
		"record",
		"rule",
		"set of",
		"string",
		"token",
		"udecimal",
		"unicode",
		"unsigned",
		"varstring",
		"varunicode"
	};
	
	private static final String[] octaveReserved5 = {
		"checkpoint",
		"deprecated",
		"failcode",
		"failmessage",
		"failure",
		"global",
		"independent",
		"onwarning",
		"persist",
		"priority",
		"recovery",
		"stored",
		"success",
		"wait",
		"when"
	};
	
	private static final String[] octaveReserved6 = {
		"#append",
		"#break",
		"#declare",
		"#demangle",
		"#end",
		"#for",
		"#getdatatype",
		"#if",
		"#inmodule",
		"#loop",
		"#mangle",
		"#onwarning",
		"#option",
		"#set",
		"#stored",
		"#uniquename",
		"#workunit"
	};
	
	public String[] getKeywords(int i) {
		switch (i) {
		case 0:
			return octaveReserved1;
		case 1:
			return octaveReserved2;
		case 2:
			return octaveReserved3;
		case 3:
			return octaveReserved4;
		case 4:
			return octaveReserved5;
		case 5:
			return octaveReserved6;
		}
		String[] emptyList = {};
		return emptyList;
	}
}
